apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ingress-controler-namespace.yaml
  - ingress-controler-helm-repo.yaml
  - ingress-controler-helm-release.yaml

  # - ingress-controler.yaml
