apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - media-service-deployment.yaml
  - media-service-namespace.yaml
  - media-service-pvc.yaml
  - media-service-services.yaml
